print('-=' * 20)
print(f'{"CALCULO DE SÁLARIO":^40}')
print('-=' * 20)
ganhoporH = float(input('Quanto você ganha por hora? R$'))
horasMes = int(input('E quantas horas você trabalha no mês? R$'))
ganhobruto = ganhoporH*horasMes
ganholiq = ganhobruto - (ganhobruto * 8 / 100) - (ganhobruto * 5 / 100)
print('-=' * 20)
print(f'{"RESULTADO DOS CALCULOS":^40}')
print('-=' * 20)
print(f'{"- Sálario Bruto":>5}', end='')
print(f'{ganhobruto:>24.2f}'.replace(".", ","))
print(f'{"- INSS"}', end='')
print(f'{(ganhobruto * 8 / 100):>33.2f}'.replace(".", ","))
print(f'{"- Sindicato":>5}', end='')
print(f'{(ganhobruto * 5 / 100):>28.2f}'.replace(".", ","))
print(f'{"- Sálario Líquido":>5}', end='')
print(f'{ganholiq:23.2f}'.replace(".", ","))
print('-=' * 20)
